### ISSUE TITLE
Tracking issue: New Blaze4D Alpha

### ISSUE THREAD

**Issue by CodingRays** [KilnGraphics/Blaze4D#71]
This is a tracking issue for the first alpha version of the new Blaze4D.

## Steps

- [ ] Complete baseline API
  - [ ] Emulation rendering #68
  - [ ] (Optional) Custom terrain rendering
- [ ] Fix build tool issues
  - [ ] Cannot build and bundle core from gradle #69
- [ ] CI pipelines issues
  - [ ] Fix CI pipelines #70
  - [ ] Automatically build universal jar for all supported platforms
